-- Generated by Palette Forge
return {
  {
    "folke/tokyonight.nvim",
    opts = {
      style = "night",
      on_colors = function(c)
        c.bg = "#222222"
        c.bg_dark = "#181818"
        c.bg_float = "#1C1C1C"
        c.bg_sidebar = "#181818"
        c.bg_statusline = "#181818"
        c.fg = "#F2F2F2"
        c.fg_dark = "#C6C6C6"
        c.fg_gutter = "#7A7A7A"
        c.border = "#008DC9"
        c.comment = "#888888"
        c.orange = "#CCCCCC"
        c.yellow = "#98E80F"
        c.red = "#BE0D22"
        c.blue = "#6ED5FF"
        c.cyan = "#00B3FF"
        c.green = "#CBD200"
        c.magenta = "#64C8F2"
      end,
      on_highlights = function(hl, c)
        hl.Normal = { bg = c.bg, fg = c.fg }
        hl.NonText = { fg = c.comment }
        hl.Comment = { fg = c.comment, italic = true }
        hl.LineNr = { fg = c.fg_gutter }
        hl.CursorLineNr = { fg = c.orange, bold = true }
        hl.CursorLine = { bg = "#1C1C1C" }
        hl.Visual = { bg = "#2C2C2C" }
        hl.StatusLine = { bg = c.bg_dark, fg = c.fg }
        hl.StatusLineNC = { bg = c.bg_dark, fg = c.comment }
        hl.WinSeparator = { fg = c.border }
        hl.TabLine = { bg = c.bg_dark, fg = c.comment }
        hl.TabLineSel = { bg = c.cyan, fg = c.bg }
        hl.TabLineFill = { bg = c.bg_dark }
        hl.DiagnosticWarn = { fg = c.yellow }
        hl.DiagnosticError = { fg = c.red }
        hl.DiagnosticInfo = { fg = c.cyan }
        hl.DiagnosticHint = { fg = c.magenta }
        hl.DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true }
        hl.DiagnosticUnderlineError = { sp = c.red, undercurl = true }
        hl.DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true }
        hl.DiagnosticUnderlineHint = { sp = c.magenta, undercurl = true }
        hl.Pmenu = { bg = "#181818", fg = c.fg_dark }
        hl.PmenuSel = { bg = c.cyan, fg = c.bg }
        hl.Search = { bg = c.orange, fg = c.bg }
        hl.IncSearch = { bg = c.yellow, fg = c.bg }
        hl.MatchParen = { fg = c.orange, bold = true }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "tokyonight" },
  },
}
